192 маска=26
252 маска =30
240 макска = 28
hq
router ospf 
ospf router-id 1.1.1.1
network 192.168.1.0/26 area 1
network 10.10.10.0/30 area 0
exit
exit
write
router ospf6
ospf router-id 0.0.0.1
area 0.0.0.0 range 2001::1:0/122
area 0.0.0.0 range 2001::7:0/126
interface ens///
ipv6 ospf area 0.0.0.0
exit
interface ens///
ipv6 ospf area 0.0.0.0
exit
exit
write
brr
router ospf 
ospf router-id 3.3.3.3
network 192.168.2.0/28 area 2
network 10.10.10.4/30 area 0
exit
exit
write
router ospf6
ospf router-id 0.0.0.3
area 0.0.0.0 range 2001::2:0/124
area 0.0.0.0 range 2001::7:0/126
interface ens///
ipv6 ospf area 0.0.0.0
exit
interface ens///
ipv6 ospf area 0.0.0.0
exit
exit
write
isp
router ospf 
ospf router-id 2.2.2.2
network 192.168.0.0/24 area 3
network 10.10.10.5/30 area 0
network 10.10.10.1/30 area 0
exit
exit
write
router ospf6
ospf router-id 0.0.0.3
area 0.0.0.0 range 2001::3:0/120
area 0.0.0.0 range 2001::7:2/126
area 0.0.0.0 range 2001::7:3/126
interface ens///
ipv6 ospf area 0.0.0.0
exit
interface ens///
ipv6 ospf area 0.0.0.0
exit
interface ens///
ipv6 ospf area 0.0.0.0
exit
exit
write
dhcp
apt install isc-dhcp-server
nano /etc/default/isc-dhcp-server
и настроить интерфейс, направленный в сторону клиента, если в сети подразумевается DHCP-relay, то 2 интерфейса в сторону клиента, и в сторону сети откуда исходит запрос.
Которые можно найти по путям nano /etc/dhcp/dhcpd.conf и nano /etc/dhcp/dhcpd6.conf соответственно
subnet 10.10.10.0 natmask 255.255.255.252 {
range 10.10.10.3 10.10.10.60;
option routers 10.10.10.1;
default-lease-time 600;
max-lease-time 7200;
}
subnet 10.10.10.0 natmask 255.255.255.252 {
range 10.10.10.3 10.10.10.60;
option routers 10.10.10.1;
default-lease-time 600;
max-lease-time 7200;
}
apt install frr
nano /etc/frr/daemons
и изменить параметры на YES для протокола OSPF
systemctl restart frr 
vtysh
Conf t
router ospf
ospf router-id x.x.x.x
network x.x.x.x/x area x
Где network 10.10.10.4/30 area 0 — относится к зоне между ISP и BR-R
а network 192.168.2.0/28 area 3 — относится к зоне между BR-R и BR-SRV
nano /etc/sysctl.conf
переменную net.ipv4.ip_forward=1 необходимо раскоментить и сохранить изменения в файле, и применить изменения командой sysctl -p
в vtysh посредством команд:
Conf t
router ospf6
Обозначить роутер ID, и зоны вокруг маршрутизатора
Рисунок 12 — настройка ospf6 
apt install isc-dhcp-server
После установки пакета следующим шагом необходимо сконфигурировать файл для указания интерфейсов прослушивания DHCP сервера зайти можно с помощью команды
nano /etc/default/isc-dhcp-server
и настроить интерфейс, направленный в сторону клиента, если в сети подразумевается DHCP-relay, то 2 интерфейса в сторону клиента, и в сторону сети откуда исходит запрос.
Далее необходимо настроить 2 конфигурационных файла для IPv4 для IPv6
Которые можно найти по путям nano /etc/dhcp/dhcpd.conf и nano /etc/dhcp/dhcpd6.conf соответственно
ddns-update-style interim — способ автообновления базы dns
authoritative — делает сервер доверенным
subnet — указание сети
range — пул адресов
option routers — шлюз по умолчанию
Примечание: после каждого изменения конфигурации необходимо перезагружать DHCP сервер для применения конфигурации
systemctl stop isc-dhcp-server
systemctl start isc-dhcp-server
А для того, чтобы после перезагрузки DHCP-сервер автоматически включался можно воспользоваться командой systemctl enable isc-dhcp-server
(subnet 192.168.1.0 netmask 255.255.255.192{
range 192.168.1.3 192.168.1.62;
option routers 192.168.1.1;
option domain-name "hq.work";
option domain-name-serveers 192.168.1.2;
Поэтому для настройки маршрутизации для клиентов можно воспользоваться утилитой radvd
которую можно установить посредством команды
apt install radvd
После установки нужно сконфигурировать файл по пути /etc/radvd.conf следующего содержания
Рисунок 18 — Пример конфигурации Radvd
где interface — это имя интерфейса направленного в локальную сеть
Min и MAX интервалы — это интервалы рассылки объявлений
AdvSendAdvert — это разрешение на выдачу объявлений от маршрутизатор клиентам
После окончания конфигурирования так же необходимо перезагрузить службу Radv
d и отправить в Enable
systemctl stop radvd
systemctl start radvd
systemctl enable radvd
(interface ens224
{Min RtrAdvInterval 3;
Max RtrAdvInterval 60;
AdvSendAdvert on;
};
Так же возможно понадобится выдать Root права для данных клиентов это можно выполнить посредством команды visudo
Измерьте пропускную способность сети между двумя узлами HQ-R-ISP по средствам утилиты iperf 3. Предоставьте описание пропускной способности канала со скриншотами.
Для начала необходимо установит утилиту iperf3 (не путать с iperf) на машины HQ-R и ISP посредством команды 
apt install iperf3	
при установке будет показано окно автоматического включения демона, нужно выбрать пункт yes 
iperf3 -c (ip адрес проверяемой машины) -i1 -t20
Составьте backup скрипты для сохранения конфигурации сетевых устройств, а именно HQ-R BR-R. Продемонстрируйте их работу.
Для начала на машинах HQ-R, BR-R создадим каталог, где будет хранится файл созданного скриптом бекапа.
Можно создать его в директории mnt
для этого пропишем mkdir /mnt/backup
Далее нам нужно создать сам файл для создания бэкап скрипта, для этого пропишем команду
touch /etc/backup.sh
зайдя в файл, необходимо прописать следующие параметры как показано на рисунке 24 или рисунке 25 (по заданию достаточно упрощённого скрипта)




